version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: gustavo
    networks:
      - postgres-pgadmin
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "gustavo@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "gustavo"
    depends_on:
      - postgres
    networks:
      - postgres-pgadmin

networks:
  postgres-pgadmin:
    driver: bridge